# Text pre-processing with Keras

In [ ]:
# import libraries
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import Embedding, GlobalAveragePooling1D
import numpy as np

## Tokenization

In [ ]:
# tokenize setences
sentences = ['The quick brown fox jumps over the lazy dog.']
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

In [ ]:
# word index
tokenizer.word_index

{'the': 1,
 'quick': 2,
 'brown': 3,
 'fox': 4,
 'jumps': 5,
 'over': 6,
 'lazy': 7,
 'dog': 8}

In [ ]:
# build train sentences
train_sequences = tokenizer.texts_to_sequences(sentences)
train_sequences = np.array(train_sequences)
print(train_sequences)

[[1 2 3 4 5 6 1 7 8]]


## Creating embedding layer

In [ ]:
# define embedding
embedding = Embedding(input_dim = len(train_sequences[0]), output_dim = 128)

In [ ]:
# create train sample using embedding
train_sample = embedding(train_sequences)

In [ ]:
# print shape
print(train_sequences.shape)
print(train_sample.shape)

(1, 9)
(1, 9, 128)


In [ ]:
# view train_sample entry
train_sample[0]

<tf.Tensor: shape=(9, 128), dtype=float32, numpy=
array([[-0.04172947, -0.02430074,  0.04249558, ...,  0.04379674,
         0.0170792 ,  0.00147563],
       [ 0.04343254,  0.0236288 ,  0.02964744, ..., -0.02272878,
         0.0318207 ,  0.01385072],
       [-0.00207211,  0.01786822,  0.0132446 , ..., -0.01227253,
         0.02559299,  0.03112444],
       ...,
       [-0.04172947, -0.02430074,  0.04249558, ...,  0.04379674,
         0.0170792 ,  0.00147563],
       [-0.03970213,  0.04337467,  0.00083563, ..., -0.00454441,
        -0.01802706, -0.00191506],
       [ 0.01867349,  0.02750683, -0.00522845, ..., -0.02240412,
        -0.03281125,  0.03209778]], dtype=float32)>

## Average across tokens

In [ ]:
GlobalAveragePooling1D()(train_sample)

<tf.Tensor: shape=(1, 128), dtype=float32, numpy=
array([[-0.00646371,  0.00459012,  0.01613507, -0.02475907, -0.00463805,
        -0.01041807, -0.00593591,  0.00839942,  0.00850757,  0.01309274,
        -0.00799438,  0.01090582,  0.0037132 ,  0.00343841,  0.00604909,
        -0.01298777, -0.02102769, -0.01624132, -0.00087732, -0.00636248,
        -0.02591994,  0.00031279,  0.00307912,  0.01628066, -0.01319968,
        -0.01258871,  0.0192764 ,  0.01244438, -0.0072722 ,  0.00124356,
         0.01868722, -0.01025032, -0.01000964,  0.00549232, -0.00665743,
        -0.00430089, -0.0131289 ,  0.01868441, -0.00756773, -0.01342515,
         0.00839466, -0.01338619,  0.00477177, -0.00321177, -0.01265965,
        -0.00621738, -0.00550857,  0.00396683, -0.02497037,  0.01376912,
         0.00507201,  0.01523754,  0.01176914, -0.00969897, -0.00133973,
         0.00807989, -0.00121588, -0.0220214 , -0.00102541,  0.01150065,
        -0.01267747, -0.00443124, -0.01885453, -0.00503646,  0.00176456,
 

## Creating Word Embeddings for more than one sentence

In [ ]:
# more than one sentence
test_corpus = [
    'The quick brown fox jumps over the lazy dog.',
    'The quick brown fox.',
    'The lazy dog.',
    'The dog.',
    'Dog and the fox.',
    'Hello, world!'
]

encoded_sentences = tokenizer.texts_to_sequences(test_corpus)
for sentence, encoded_sentence in zip(test_corpus, encoded_sentences):
    print(sentence, encoded_sentence)

The quick brown fox jumps over the lazy dog. [1, 2, 3, 4, 5, 6, 1, 7, 8]
The quick brown fox. [1, 2, 3, 4]
The lazy dog. [1, 7, 8]
The dog. [1, 8]
Dog and the fox. [8, 1, 4]
Hello, world! []


## Padding sentences

As lengths of corpus sentences are not equal so we need to add padding.

In [ ]:
# compute max length
max_sequence_len = max([len(encoded_sentence) for encoded_sentence in encoded_sentences])
max_sequence_len

9

In [ ]:
X = pad_sequences(encoded_sentences, maxlen=max_sequence_len)
X

array([[1, 2, 3, 4, 5, 6, 1, 7, 8],
       [0, 0, 0, 0, 0, 1, 2, 3, 4],
       [0, 0, 0, 0, 0, 0, 1, 7, 8],
       [0, 0, 0, 0, 0, 0, 0, 1, 8],
       [0, 0, 0, 0, 0, 0, 8, 1, 4],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

## Add embedding layer

In [ ]:
X.shape

(6, 9)

In [ ]:
# X embedding computation
X_em = embedding(X)

In [ ]:
X_em.shape

TensorShape([6, 9, 128])

In [ ]:
X_em

<tf.Tensor: shape=(6, 9, 128), dtype=float32, numpy=
array([[[-0.00675882,  0.02704122,  0.02494246, ...,  0.03058055,
         -0.00274641,  0.010567  ],
        [-0.00099293,  0.00633718,  0.03035268, ..., -0.02737125,
          0.01473879,  0.04386456],
        [ 0.02548711, -0.04460666, -0.03255689, ..., -0.01298981,
          0.00661622,  0.02378266],
        ...,
        [-0.00675882,  0.02704122,  0.02494246, ...,  0.03058055,
         -0.00274641,  0.010567  ],
        [-0.03463781, -0.00560901,  0.04400753, ...,  0.01335274,
         -0.04741051, -0.04433268],
        [-0.04069146,  0.02949848, -0.04637171, ..., -0.04578247,
         -0.04775527,  0.01276716]],

       [[-0.04979328, -0.03621882,  0.02436706, ..., -0.0336159 ,
          0.01909152, -0.00570704],
        [-0.04979328, -0.03621882,  0.02436706, ..., -0.0336159 ,
          0.01909152, -0.00570704],
        [-0.04979328, -0.03621882,  0.02436706, ..., -0.0336159 ,
          0.01909152, -0.00570704],
        ...,
 

## Average across tokens

In [ ]:
z = GlobalAveragePooling1D()(X_em)
z.shape

TensorShape([6, 128])